var readlineSync = require('readline-sync')
console.log("EMPRÉSTIMO DA CREUZA")
console.log("===================")
var emprestimo = Number(readlineSync.question("Valor total do empréstimo: R$"))
var parcelas = Number(readlineSync.question("Quantidade de parcelas: "))
console.clear()
console.log("EMPRÉSTIMO DA CREUZA")
console.log("===================")
console.log(`Você pagará ${parcelas} parcelas de R$${((emprestimo + (emprestimo * 0.2)) / parcelas).toFixed(2)}`)