function capitalizarPalavrasArray(array) {
    return array.map(str => {
      return str.toLowerCase().replace(/(?:^|\s)\w/g, function(letra) {
        return letra.toUpperCase();
      });
    });
  }
  
  const strings = ["IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - ARARIPINA (PCPE - IITB - RASTRO - ARARIP),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - ARCOVERDE (PCPE - IITB - RASTRO - ARCOV),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - BELO JARDIM (PCPE - IITB - RASTRO- B JARDIM),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - CARUARU (PCPE - IITB - RASTRO - CARUARU),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - GARANHUNS (PCPE - IITB - RASTRO - GARANHU),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - GRAVATÁ (PCPE - IITB - RASTRO - GRAVATÁ),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - NAZARÉ DA MATA (PCPE - IITB - RASTRO - NAZARE),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - PALMARES (PCPE - IITB - RASTRO - PALMARE),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - PETROLINA (PCPE - IITB - RASTRO - PETROLI),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - SALGUEIRO (PCPE - IITB - RASTRO - SALGUE),",
  "IITB - RASTRO DO INSTITUTO DE IDENTIFICAÇÃO TAVARES BURIL - SERRA TALHADA (PCPE - IITB - RASTRO - SERRA T),",
  "IITB - UNIDADE CRIMINAL - DIVISÃO DE TÉCNICA DE IDENTIFICAÇÃO CRIMINAL (PCPE - IITB - DIVTEC),",];
  
  const stringsFormatadas = capitalizarPalavrasArray(strings);
  for(let each of stringsFormatadas){
   console.log(each)
  }
  console.log(stringsFormatadas);